<a href="https://colab.research.google.com/github/muskanmathur2706-cloud/car-resale-value-prediction-using-tensorflow/blob/main/CarResale_value_prediction_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Import Libraries and Load the Dataset

### 1. Load files to Google Colab

In [ ]:
from google.colab import files
uploaded = files.upload()

### 2. Import Libraries

In [ ]:
import numpy as  np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

### 3. Creating a DataFrame

In [ ]:
df = pd.read_csv('cars_sorted.csv')

In [ ]:
df.head()

,Unnamed: 0,Manufacturer,Model,Sales_in_thousands,four_year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,0,Acura,Integra,16.919,16.360,Passenger,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,1,Acura,TL,39.384,19.875,Passenger,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,2,Acura,CL,14.114,18.225,Passenger,22.799,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,72.030917
3,3,Acura,RL,8.588,29.725,Passenger,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,4,Audi,A4,20.397,22.255,Passenger,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639

## 2. Data Preprocessing

In this Dataset, there are no NAN or Missing Values. So, no Data Preprocessing is needed.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              157 non-null    int64
 1   Manufacturer            157 non-null    object
 2   Model                   157 non-null    object
 3   Sales_in_thousands      157 non-null    float64
 4   four_year_resale_value  157 non-null    float64
 5   Vehicle_type            157 non-null    object
 6   Price_in_thousands      157 non-null    float64
 7   Engine_size             157 non-null    float64
 8   Horsepower              157 non-null    float64
 9   Wheelbase               157 non-null    float64
 10  Width                   157 non-null    float64
 11  Length                  157 non-null    float64
 12  Curb_weight             157 non-null    float64
 13  Fuel_capacity           157 non-null    float64
 14  Fuel_efficiency         157 non-null    float64
 15  Latest_Launch           157 non-null    object
 16  Power_perf_factor       157 non-null    float64
dtypes: float64(12), int64(1), object(4)
memory usage: 21.0+ KB

## 3. Data Visualisation

In [ ]:
sns.scatterplot(x='Engine Size', y='Price', data=df, label='Engine Size', color='blue')
sns.scatterplot(x='Horsepower', y='Price', data=df, label='Horsepower', color='green')
sns.scatterplot(x='PPF', y='Price', data=df, label='PPF', color='red')

plt.xlabel('Engine Size/Horsepower/PPF')
plt.ylabel('Price (in Lacs)')

plt.title('Relationship of Engine Size, Horsepower, PPF with Price (in Lacs)')

plt.legend()
plt.show()

## 4. Feature Encoding

We need to encode Vehicle Type using One-Hot Encoding because the data is Nominal.

In [ ]:
df['Vehicle_type'].unique()

array(['Passenger', 'Car'], dtype=object)

In [ ]:
df = pd.get_dummies(df, columns=['Vehicle_type'], drop_first=True)

In [ ]:
df.head()

,Unnamed: 0,Manufacturer,Model,Sales_in_thousands,four_year_resale_value,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor,Vehicle_type_Passenger
0,0,Acura,Integra,16.919,16.360,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150,True
1,1,Acura,TL,39.384,19.875,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778,True
2,2,Acura,CL,14.114,18.225,22.799,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,72.030917,True
3,3,Acura,RL,8.588,29.725,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779,True
4,4,Audi,A4,20.397,22.255,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639,True

We do not encode Manufacturer and Model because it is not a feature in the final dataset.

## 5. Train-Test Split

### 1. Selecting Input (Features) for ML Model

In [ ]:
X = df.drop(['Manufacturer', 'Model', 'Unnamed: 0', 'Latest_Launch', 'four_year_resale_value'], axis = 1)

X.head()

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Power_perf_factor,Vehicle_type_Passenger
0,16.919,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,58.280150,True
1,39.384,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,91.370778,True
2,14.114,22.799,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,72.030917,True
3,8.588,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,91.389779,True
4,20.397,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,62.777639,True

### 2. Selecting Output (Target) for ML Model

In [ ]:
y = df['four_year_resale_value']

y.head()

0    16.360
1    19.875
2    18.225
3    29.725
4    22.255
Name: four_year_resale_value, dtype: float64

### 3. Import Train-Test Split from SK Learn for Train-Test Split

In [ ]:
from sklearn.model_selection import train_test_split

### 4. Split the Input and Output Features using SK Learn

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
print("X-Train Shape : ", X_train.shape)
print("X-Test Shape : ", X_test.shape)
print("y-Train Shape : ", y_train.shape)
print("y-Test Shape : ", y_test.shape)

X-Train Shape :  (125, 12)
X-Test Shape :  (32, 12)
y-Train Shape :  (125,)
y-Test Shape :  (32,)

## 6. Feature Scaling

In Neural Networks, we need to perform Feature Scaling because it is based Gradient-based Learning.

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## 7. Neural Network using TensorFlow

1. Import TensorFlow and Keras

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input

2. Making an object of the Neural Network Model

In [ ]:
model = Sequential()

3. Create the Layers of the Neural Network

In [ ]:
# Creating the Input Layer
model.add(Input(shape = (12,)))

# Creating the First Hidden Layer
model.add(Dense(1028, activation = 'relu'))

# Creating the Second Hidden Layer
model.add(Dense(512, activation = 'relu'))

# Creating the Third Hidden Layer
model.add(Dense(256, activation = 'relu'))

# Creating the Fourth Hidden Layer
model.add(Dense(128, activation = 'relu'))

# Creating the Output Layer
model.add(Dense(1, activation = 'linear'))

In [ ]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_33 (Dense)                │ (None, 1028)           │        13,364 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ (None, 512)            │       526,848 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_36 (Dense)                │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_37 (Dense)                │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 704,565 (2.69 MB)

 Trainable params: 704,565 (2.69 MB)

 Non-trainable params: 0 (0.00 B)

4. Compile the Neural Network

In [ ]:
model.compile(loss = 'mse', metrics = ['r2_score'], optimizer = 'Adam')

5. Train the Neural Network

In [ ]:
model.fit(X_train, y_train, epochs = 100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 298.2141 - r2_score: -3.9556
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 205.7169 - r2_score: -2.4185
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 67.4035 - r2_score: -0.1201
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 84.6271 - r2_score: -0.4063
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 49.8215 - r2_score: 0.1721
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 61.0561 - r2_score: -0.0146
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 43.2351 - r2_score: 0.2815
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 49.4574 - r2_score: 0.1781
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 43.7105 - r2_score: 0.2736
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 41.5893 - r2_score: 0.3089
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 36.5524 - r2_score: 0.3926
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 35.5985 - r2_score: 0.4084
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 33.4168 - r2_score: 0.4447
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 32.9241 - r2_score: 0.4529
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 31.7490 - r2_score: 0.4724
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 30.5513 - r2_score: 0.4923
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 30.2657 - r2_score: 0.4971
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 29.6798 - r2_score: 0.5068
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 29.1526 - r2_score: 0.5156
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 29.0416 - r2_score: 0.5174
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 29.0641 - r2_score: 0.5170
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 27.7938 - r2_score: 0.5381
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 27.8370 - r2_score: 0.5374
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 27.9361 - r2_score: 0.5358
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 26.5646 - r2_score: 0.5586
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 27.3625 - r2_score: 0.5453
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 25.9131 - r2_score: 0.5694
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 26.6426 - r2_score: 0.5573
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 26.2943 - r2_score: 0.5631
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.0289 - r2_score: 0.5675
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 25.9436 - r2_score: 0.5689
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 26.5643 - r2_score: 0.5586
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 25.0932 - r2_score: 0.5830
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 25.2660 - r2_score: 0.5801
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 26.0736 - r2_score: 0.5667
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 25.2210 - r2_score: 0.5809
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 25.2505 - r2_score: 0.5804
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 26.9462 - r2_score: 0.5522
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 24.6652 - r2_score: 0.5901
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 26.6259 - r2_score: 0.5575
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 25.5640 - r2_score: 0.5752
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 24.7705 - r2_score: 0.5884
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 25.6750 - r2_score: 0.5733
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 25.9340 - r2_score: 0.5690
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 26.0285 - r2_score: 0.5675
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 25.5805 - r2_score: 0.5749
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 25.6537 - r2_score: 0.5737
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 23.9435 - r2_score: 0.6021
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 23.9313 - r2_score: 0.6023
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 24.4302 - r2_score: 0.5940
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 23.9759 - r2_score: 0.6016
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 23.9358 - r2_score: 0.6022
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 23.2822 - r2_score: 0.6131
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 23.6779 - r2_score: 0.6065
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 23.0780 - r2_score: 0.6165
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 23.1558 - r2_score: 0.6152
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 23.0325 - r2_score: 0.6173
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 23.2913 - r2_score: 0.6130
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 22.7274 - r2_score: 0.6223
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 23.4743 - r2_score: 0.6099
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 22.4209 - r2_score: 0.6274
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 22.7940 - r2_score: 0.6212
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 22.5405 - r2_score: 0.6254
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 22.3102 - r2_score: 0.6293
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 22.8869 - r2_score: 0.6197
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 22.4355 - r2_score: 0.6272
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 23.2935 - r2_score: 0.6129
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 22.8640 - r2_score: 0.6201
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 21.3941 - r2_score: 0.6445
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 24.0011 - r2_score: 0.6012
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 22.8759 - r2_score: 0.6199
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 23.9207 - r2_score: 0.6025
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 20.7116 - r2_score: 0.6558
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 22.5764 - r2_score: 0.6248
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 20.8424 - r2_score: 0.6536
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 23.0642 - r2_score: 0.6167
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 23.4541 - r2_score: 0.6102
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 21.8730 - r2_score: 0.6365
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 22.1418 - r2_score: 0.6321
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 21.2828 - r2_score: 0.6463
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 20.7497 - r2_score: 0.6552
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 22.1140 - r2_score: 0.6325
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 20.4442 - r2_score: 0.6603
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 21.2579 - r2_score: 0.6467
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 20.3773 - r2_score: 0.6614
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 20.0923 - r2_score: 0.6661
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 22.0982 - r2_score: 0.6328
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 21.0832 - r2_score: 0.6496
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 21.5521 - r2_score: 0.6419
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 22.7664 - r2_score: 0.6217
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 19.8870 - r2_score: 0.6695
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 18.6604 - r2_score: 0.6899
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 20.0929 - r2_score: 0.6661
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 18.8336 - r2_score: 0.6870
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 18.7945 - r2_score: 0.6877
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 18.7938 - r2_score: 0.6877
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 18.4735 - r2_score: 0.6930
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 19.1878 - r2_score: 0.6811
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 19.1747 - r2_score: 0.6814
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 20.5676 - r2_score: 0.6582

6. Predit the Values using the Neural Network

In [ ]:
y_pred = model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

In [ ]:
print(y_pred)

[[40.983364 ]
 [12.334104 ]
 [10.318781 ]
 [15.70737  ]
 [19.482727 ]
 [14.8751135]
 [39.79055  ]
 [21.844265 ]
 [26.57687  ]
 [10.670521 ]
 [10.489884 ]
 [11.265285 ]
 [21.725922 ]
 [16.649662 ]
 [33.464355 ]
 [13.434566 ]
 [41.233418 ]
 [11.633485 ]
 [26.482395 ]
 [19.044197 ]
 [11.1918955]
 [19.426785 ]
 [16.78006  ]
 [21.400885 ]
 [10.250848 ]
 [11.526696 ]
 [13.134157 ]
 [18.805477 ]
 [10.271054 ]
 [25.312426 ]
 [10.2139845]
 [19.558481 ]]

7. Calculate the Value of Weight and Bias of the Neural Network

In [ ]:
model.layers[1].get_weights()

[array([[ 0.01683628,  0.00021012, -0.01223128, ..., -0.07633796,
         -0.02294087, -0.01860962],
        [-0.05268375,  0.05446018, -0.05924849, ..., -0.00899375,
         -0.02703546, -0.0369086 ],
        [ 0.00864687,  0.01971454, -0.03925876, ...,  0.03133345,
         -0.03514823, -0.03090433],
        ...,
        [-0.01699309, -0.0515452 ,  0.00407949, ...,  0.0796582 ,
          0.06236031, -0.01806922],
        [ 0.01848196, -0.00294324,  0.01973719, ...,  0.00308076,
          0.02279192,  0.00877161],
        [ 0.02034729,  0.03624387, -0.00837366, ...,  0.03085426,
         -0.05401876,  0.1421568 ]], dtype=float32),
 array([ 0.        , -0.00439136,  0.        ,  0.01600168, -0.00900712,
         0.        , -0.00695722, -0.00994825, -0.00604735,  0.01484067,
         0.01330832, -0.00604889,  0.        , -0.0061251 ,  0.00823834,
        -0.0055587 , -0.00570244, -0.00789771,  0.01215894, -0.0075631 ,
         0.        ,  0.01575922, -0.00580709,  0.01599553, -0.0084779 ,
         0.        ,  0.00523322,  0.        , -0.00956049, -0.00061183,
         0.01661712,  0.00516653,  0.01599668,  0.00767982, -0.01129431,
        -0.00626123, -0.00600522,  0.01452143, -0.00769819,  0.00917684,
        -0.00371978,  0.        ,  0.0148478 , -0.00600535,  0.01331597,
        -0.00701185, -0.00621216,  0.01555088,  0.        ,  0.01015999,
        -0.00751736, -0.00600411,  0.01480992,  0.01700627, -0.00764256,
        -0.00824093, -0.00605644,  0.01093454,  0.        ,  0.        ,
        -0.01286397,  0.00969315,  0.01561744,  0.01204034, -0.00600394,
        -0.0070175 , -0.00476556, -0.0056498 ,  0.01719142,  0.01582728,
        -0.00600518,  0.00743291, -0.00784655, -0.00447763,  0.01582251,
         0.        , -0.01335553,  0.01689945, -0.00581866,  0.01472504,
         0.00968014,  0.        ,  0.01505163,  0.0117323 ,  0.01725179,
        -0.00762021, -0.0088535 ,  0.01485738,  0.01655891, -0.00888368,
        -0.00534634,  0.0049884 , -0.00884561, -0.00442992, -0.00736411,
         0.01413609,  0.        ,  0.        , -0.00326389,  0.00950631,
        -0.00885658,  0.01048698,  0.01287089, -0.00600546, -0.00600531,
        -0.01089694,  0.00696157, -0.00600529, -0.00741659,  0.01597813,
         0.01427914,  0.00375301, -0.0052303 ,  0.01578229,  0.        ,
        -0.00376089,  0.01415222, -0.00911884,  0.00216025,  0.01277218,
         0.01480083, -0.00718123, -0.00845732,  0.00189692,  0.01586873,
         0.        ,  0.00953599, -0.00834624,  0.01330384,  0.01067184,
         0.01574425,  0.01557164, -0.0068105 , -0.00788902, -0.00522849,
        -0.00600528,  0.00484025,  0.01511541,  0.01637091, -0.0103091 ,
         0.01571912,  0.01231163,  0.        , -0.00667834,  0.00583044,
        -0.00600982, -0.00464813,  0.01582416,  0.01484597, -0.01085829,
        -0.0063052 ,  0.01561971,  0.0141759 , -0.00611818,  0.01369567,
         0.01393078,  0.00918132,  0.01701708, -0.0061044 , -0.00614516,
         0.01400981,  0.01598359, -0.0054073 ,  0.01586759,  0.00651967,
        -0.00642612,  0.01371552,  0.00443322, -0.00327768,  0.00718739,
        -0.00569939,  0.0115459 , -0.01248039,  0.        ,  0.        ,
         0.01133454,  0.01397531, -0.01474017, -0.01382989,  0.        ,
         0.01300902,  0.00116497,  0.01666247,  0.01243823, -0.00881601,
         0.        ,  0.        ,  0.01629125, -0.00586329,  0.0155729 ,
        -0.0053426 ,  0.01221144, -0.0068184 , -0.00458058,  0.01384569,
         0.01065813, -0.00894115, -0.00438819,  0.01668167,  0.01732073,
         0.01048317, -0.00600543, -0.00555543,  0.00358337,  0.        ,
         0.00752991, -0.00648792,  0.        ,  0.        ,  0.01660361,
         0.        ,  0.0149167 , -0.00542156, -0.00425674,  0.01254   ,
         0.01708683, -0.00534659, -0.00516836, -0.00893128, -0.00984083,
         0.        ,  0.0106314 , -0.00833682, -0.0060047 , -0.00845894,
         0.01592642,  0.        , -0.00600537, -0.00600545,  0.01582553,
        -0.00600543,  0.01661325,  0.01504858, -0.00600544, -0.00600537,
         0.008618  , -0.00600546,  0.01249098, -0.00772534,  0.013065  ,
         0.00998383, -0.00706637, -0.00950602, -0.00672914,  0.00930007,
        -0.00600501, -0.00600498, -0.01050425,  0.01584383, -0.00555241,
         0.01370285, -0.00738649, -0.00636628, -0.00570433,  0.01653114,
        -0.00958405, -0.00766223, -0.00268519,  0.01368512,  0.01549473,
        -0.00870038,  0.00522275,  0.01509294,  0.00806002, -0.00600387,
        -0.00600529, -0.00744036,  0.01554829, -0.00585663,  0.01202204,
         0.        ,  0.01299183, -0.00577396,  0.        ,  0.00405331,
         0.0111819 , -0.00798649, -0.00588477,  0.01626411, -0.0053661 ,
        -0.00777768, -0.00600498,  0.00493231,  0.01476744, -0.0044162 ,
        -0.00787235,  0.01677607, -0.00600533,  0.01528967,  0.01158798,
        -0.00292634,  0.01639261,  0.01591149, -0.0089228 ,  0.01956808,
        -0.00984703,  0.01334261,  0.01485049,  0.01709855,  0.01611578,
         0.01331699,  0.01461525, -0.00600539,  0.01064866,  0.        ,
        -0.00506326, -0.00893774, -0.00841533, -0.00694275,  0.01610607,
         0.01439223,  0.01171684,  0.01353273,  0.01561906, -0.00599966,
         0.0152334 , -0.00585754,  0.01586441,  0.01757436, -0.00687827,
        -0.00629895, -0.00835014,  0.00594579, -0.00483824,  0.01555817,
         0.01574286, -0.00442255, -0.01572974, -0.00598039,  0.        ,
         0.01052798, -0.00678985,  0.01604363,  0.        , -0.00759526,
         0.        , -0.00600505,  0.01438348,  0.01007421,  0.01459643,
         0.01634161,  0.        , -0.01280834, -0.00673438,  0.01684098,
         0.00868696, -0.00641112,  0.01730847, -0.00917996, -0.00808532,
        -0.00600507, -0.00600236, -0.00555868, -0.0060048 , -0.00643083,
        -0.00555788,  0.        , -0.00834253,  0.00953129,  0.01052854,
         0.02940723,  0.00957093, -0.00600498, -0.0074431 , -0.00600521,
         0.01376726,  0.01660437, -0.00555673,  0.01073398,  0.01347851,
         0.        , -0.00688315, -0.0087556 , -0.00480515, -0.00600543,
         0.01434752, -0.00600544,  0.01385174, -0.00640994,  0.01338732,
         0.01419326,  0.01317457, -0.00600505, -0.01594348,  0.0150436 ,
         0.        , -0.00023873,  0.01512785, -0.00555882,  0.        ,
        -0.00792913,  0.01121844,  0.01698027, -0.0066843 , -0.01194347,
         0.00823048, -0.00706296, -0.00654232,  0.01620135,  0.01666278,
         0.        , -0.00607325, -0.0041586 , -0.00428696,  0.01536445,
        -0.00923403, -0.00600488, -0.00585271, -0.00712948, -0.01046039,
         0.00990443,  0.        ,  0.        ,  0.01493981, -0.00927883,
         0.        , -0.0084024 ,  0.01257648,  0.        ,  0.01304717,
        -0.00809335,  0.01649283, -0.00796384,  0.01637302, -0.00853473,
         0.        , -0.00600542, -0.00790722,  0.01617305, -0.00600538,
        -0.00601459,  0.01062401,  0.00660947, -0.00600541,  0.        ,
        -0.00630789, -0.0043386 ,  0.01366073, -0.00726277,  0.00305064,
         0.01230959,  0.00407748, -0.00505129, -0.00600542,  0.01540685,
        -0.00605393, -0.00600543,  0.00929076, -0.0072393 ,  0.01632506,
        -0.00569107,  0.01465839, -0.00625607, -0.00823617,  0.01611991,
         0.01059439, -0.0060049 , -0.01143731, -0.00723285,  0.        ,
        -0.00770179,  0.01362111, -0.00534585, -0.00826801,  0.01410311,
         0.01592326,  0.        , -0.00674749, -0.00550306, -0.00714387,
        -0.00693776,  0.        , -0.00637138,  0.        ,  0.01454482,
        -0.00975044, -0.00714746, -0.00555883,  0.0111783 , -0.0039776 ,
         0.01426624,  0.01696654,  0.        ,  0.01545515, -0.01135162,
        -0.00742772, -0.00111331, -0.00633769, -0.00600543, -0.00952682,
         0.01237862, -0.0055577 ,  0.01397215,  0.00712397,  0.01614261,
        -0.00822677, -0.00707046,  0.00671573,  0.01474425, -0.00596107,
        -0.00600511, -0.00505383, -0.00673015, -0.00635122,  0.01159155,
         0.01534993,  0.01472687,  0.00694777, -0.00611859,  0.00720287,
         0.        ,  0.01603469], dtype=float32)]

## 8. Model Evaluation

1. Importing Performance Metrics to Evaluate the Model Performance

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

2. Evaluating the Model Performance

In [ ]:
r2s = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

In [ ]:
print('R2 Score - ',r2s)
print('Mean Absolute Error - ',mae)
print('Mean Absolute Error - ',mse)

R2 Score -  0.6444351596553826
Mean Absolute Error -  6.0194509935379035
Mean Absolute Error -  86.56615978927707